 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/public_records", type: :request do
  
  # PublicRecord. As you add validations to PublicRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PublicRecord.create! valid_attributes
      get public_records_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      public_record = PublicRecord.create! valid_attributes
      get public_record_url(public_record)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_public_record_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      public_record = PublicRecord.create! valid_attributes
      get edit_public_record_url(public_record)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PublicRecord" do
        expect {
          post public_records_url, params: { public_record: valid_attributes }
        }.to change(PublicRecord, :count).by(1)
      end

      it "redirects to the created public_record" do
        post public_records_url, params: { public_record: valid_attributes }
        expect(response).to redirect_to(public_record_url(PublicRecord.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PublicRecord" do
        expect {
          post public_records_url, params: { public_record: invalid_attributes }
        }.to change(PublicRecord, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post public_records_url, params: { public_record: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested public_record" do
        public_record = PublicRecord.create! valid_attributes
        patch public_record_url(public_record), params: { public_record: new_attributes }
        public_record.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the public_record" do
        public_record = PublicRecord.create! valid_attributes
        patch public_record_url(public_record), params: { public_record: new_attributes }
        public_record.reload
        expect(response).to redirect_to(public_record_url(public_record))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        public_record = PublicRecord.create! valid_attributes
        patch public_record_url(public_record), params: { public_record: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested public_record" do
      public_record = PublicRecord.create! valid_attributes
      expect {
        delete public_record_url(public_record)
      }.to change(PublicRecord, :count).by(-1)
    end

    it "redirects to the public_records list" do
      public_record = PublicRecord.create! valid_attributes
      delete public_record_url(public_record)
      expect(response).to redirect_to(public_records_url)
    end
  end
end
